/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TppmIncluirEmpregadoBox.java
 *
 * Created on Jul 28, 2013, 11:38:46 AM
 */
package tppm.views;

import javax.swing.JOptionPane;
import tppm.controllers.EmpregadoController;


/**
 *
 * @author Tiago Neves + Pedro Jardim
 */
public class TppmIncluirEmpregadoBox extends javax.swing.JFrame {

    EmpregadoController empregadoController;
    
    /** Creates new form TppmIncluirEmpregadoBox */
    public TppmIncluirEmpregadoBox() {
        initComponents();
        empregadoController = new EmpregadoController();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        nomeCompletoInput = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfInput = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox();
        dataNascimentoLabel = new javax.swing.JLabel();
        dataNascimentoInput = new javax.swing.JTextField();
        dataAdmissaoLabel = new javax.swing.JLabel();
        dataAdmissaoInput = new javax.swing.JTextField();
        salarioLabel = new javax.swing.JLabel();
        salarioInput = new javax.swing.JTextField();
        dataDesligamentoInput = new javax.swing.JTextField();
        dataDesligamentoLabel = new javax.swing.JLabel();
        btIncluirEmpregado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tppm.views.TppmApp.class).getContext().getResourceMap(TppmIncluirEmpregadoBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        nomeLabel.setText(resourceMap.getString("nomeLabel.text")); // NOI18N
        nomeLabel.setName("nomeLabel"); // NOI18N

        nomeCompletoInput.setText(resourceMap.getString("nomeCompletoInput.text")); // NOI18N
        nomeCompletoInput.setName("nomeCompletoInput"); // NOI18N

        cpfLabel.setText(resourceMap.getString("cpfLabel.text")); // NOI18N
        cpfLabel.setName("cpfLabel"); // NOI18N

        cpfInput.setText(resourceMap.getString("cpfInput.text")); // NOI18N
        cpfInput.setName("cpfInput"); // NOI18N

        sexoLabel.setText(resourceMap.getString("sexoLabel.text")); // NOI18N
        sexoLabel.setName("sexoLabel"); // NOI18N

        sexoComboBox.setModel(EmpregadoController.obtemComboSexoModel());
        sexoComboBox.setName("sexoComboBox"); // NOI18N

        dataNascimentoLabel.setText(resourceMap.getString("dataNascimentoLabel.text")); // NOI18N
        dataNascimentoLabel.setName("dataNascimentoLabel"); // NOI18N

        dataNascimentoInput.setText(resourceMap.getString("dataNascimentoInput.text")); // NOI18N
        dataNascimentoInput.setName("dataNascimentoInput"); // NOI18N

        dataAdmissaoLabel.setText(resourceMap.getString("dataAdmissaoLabel.text")); // NOI18N
        dataAdmissaoLabel.setName("dataAdmissaoLabel"); // NOI18N

        dataAdmissaoInput.setName("dataAdmissaoInput"); // NOI18N

        salarioLabel.setText(resourceMap.getString("salarioLabel.text")); // NOI18N
        salarioLabel.setName("salarioLabel"); // NOI18N

        salarioInput.setText(resourceMap.getString("salarioInput.text")); // NOI18N
        salarioInput.setName("salarioInput"); // NOI18N

        dataDesligamentoInput.setText(resourceMap.getString("dataDesligamentoInput.text")); // NOI18N
        dataDesligamentoInput.setName("dataDesligamentoInput"); // NOI18N

        dataDesligamentoLabel.setText(resourceMap.getString("dataDesligamentoLabel.text")); // NOI18N
        dataDesligamentoLabel.setName("dataDesligamentoLabel"); // NOI18N

        btIncluirEmpregado.setText(resourceMap.getString("btIncluirEmpregado.text")); // NOI18N
        btIncluirEmpregado.setName("btIncluirEmpregado"); // NOI18N
        btIncluirEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirEmpregadoActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btIncluirEmpregado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeLabel)
                            .addComponent(cpfLabel)
                            .addComponent(sexoLabel)
                            .addComponent(dataNascimentoLabel)
                            .addComponent(dataAdmissaoLabel)
                            .addComponent(salarioLabel)
                            .addComponent(dataDesligamentoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dataDesligamentoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salarioInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataAdmissaoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataNascimentoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeCompletoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataAdmissaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataAdmissaoLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDesligamentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDesligamentoLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btIncluirEmpregado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirEmpregadoActionPerformed
        String cpf = cpfInput.getText();
        String nome = nomeCompletoInput.getText();
        String sexo = (String) sexoComboBox.getSelectedItem();
        String dataNascimento = dataNascimentoInput.getText();
        String dataAdmissao = dataAdmissaoInput.getText();
        String salarioAtual = salarioInput.getText();
        String dataDesligamento = dataDesligamentoInput.getText();
        
        try{
            empregadoController.incluirEmpregado(cpf, nome, sexo, dataNascimento, dataAdmissao, salarioAtual, dataDesligamento);
            exibeMensagem("Empregado incluido com sucesso!");
            closeIncluirEmpregadoBox();
        } catch(Exception e){
            exibeErro(e.getMessage());
        }
    }//GEN-LAST:event_btIncluirEmpregadoActionPerformed

    private void exibeErro(String mensagem){
        JOptionPane.showMessageDialog(this, mensagem, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    private void exibeMensagem(String mensagem){
        JOptionPane.showMessageDialog(this, mensagem, "", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void closeIncluirEmpregadoBox() {
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TppmIncluirEmpregadoBox().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluirEmpregado;
    private javax.swing.JTextField cpfInput;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField dataAdmissaoInput;
    private javax.swing.JLabel dataAdmissaoLabel;
    private javax.swing.JTextField dataDesligamentoInput;
    private javax.swing.JLabel dataDesligamentoLabel;
    private javax.swing.JTextField dataNascimentoInput;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeCompletoInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField salarioInput;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JComboBox sexoComboBox;
    private javax.swing.JLabel sexoLabel;
    // End of variables declaration//GEN-END:variables
}
