/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TppmResultadoCalculoEmprestimoBox.java
 *
 * Created on Jul 29, 2013, 8:35:59 PM
 */
package tppm.views;

import tppm.domains.Emprestimo;
import tppm.utils.Utils;

/**
 *
 * @author Tiago
 */
public class TppmResultadoCalculoEmprestimoBox extends javax.swing.JFrame {

    /** Creates new form TppmResultadoCalculoEmprestimoBox */
    public TppmResultadoCalculoEmprestimoBox(Emprestimo emprestimo) {
        initComponents();
        preencherCamposComResultadoDoCalculoDoEmprestimo(emprestimo);
    }
    
    private void preencherCamposComResultadoDoCalculoDoEmprestimo(Emprestimo emprestimo){
        nomeEmpregadoInput.setText(emprestimo.getEmpregado().getNome());
        valorEmprestimoInput.setText(Utils.arredondarDouble(emprestimo.getValorSolicitado()).toString());
        valorPrestacaoInput.setText(Utils.arredondarDouble(emprestimo.getValorPrestacao()).toString());
        valorTotalInput.setText(Utils.arredondarDouble(emprestimo.getValorTotalPagar()).toString());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeEmpregadoInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorPrestacaoInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valorEmprestimoInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valorTotalInput = new javax.swing.JTextField();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tppm.views.TppmApp.class).getContext().getResourceMap(TppmResultadoCalculoEmprestimoBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        nomeEmpregadoInput.setBackground(resourceMap.getColor("nomeEmpregadoInput.background")); // NOI18N
        nomeEmpregadoInput.setEditable(false);
        nomeEmpregadoInput.setText(resourceMap.getString("nomeEmpregadoInput.text")); // NOI18N
        nomeEmpregadoInput.setName("nomeEmpregadoInput"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        valorPrestacaoInput.setBackground(resourceMap.getColor("valorPrestacaoInput.background")); // NOI18N
        valorPrestacaoInput.setEditable(false);
        valorPrestacaoInput.setText(resourceMap.getString("valorPrestacaoInput.text")); // NOI18N
        valorPrestacaoInput.setName("valorPrestacaoInput"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        valorEmprestimoInput.setBackground(resourceMap.getColor("valorEmprestimoInput.background")); // NOI18N
        valorEmprestimoInput.setEditable(false);
        valorEmprestimoInput.setText(resourceMap.getString("valorEmprestimoInput.text")); // NOI18N
        valorEmprestimoInput.setName("valorEmprestimoInput"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        valorTotalInput.setBackground(resourceMap.getColor("valorTotalInput.background")); // NOI18N
        valorTotalInput.setEditable(false);
        valorTotalInput.setText(resourceMap.getString("valorTotalInput.text")); // NOI18N
        valorTotalInput.setName("valorTotalInput"); // NOI18N

        btFechar.setText(resourceMap.getString("btFechar.text")); // NOI18N
        btFechar.setName("btFechar"); // NOI18N
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeEmpregadoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorEmprestimoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(valorPrestacaoInput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(valorTotalInput, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(325, Short.MAX_VALUE)
                        .addComponent(btFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeEmpregadoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorEmprestimoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valorPrestacaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(valorTotalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomeEmpregadoInput;
    private javax.swing.JTextField valorEmprestimoInput;
    private javax.swing.JTextField valorPrestacaoInput;
    private javax.swing.JTextField valorTotalInput;
    // End of variables declaration//GEN-END:variables
}
