/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TppmAlterarEmpregadoBox.java
 *
 * Created on Jul 29, 2013, 4:47:51 AM
 */
package tppm.views;

import javax.swing.JFrame;
import tppm.controllers.EmpregadoController;
import tppm.domains.Empregado;
import tppm.exceptions.DAOExceptions.EmpregadoDAOException;
import tppm.exceptions.validacaoEmpregadoExceptions.ValidacaoEmpregadoException;
import tppm.utils.Utils;

/**
 *
 * @author Tiago
 */
public class TppmAlterarEmpregadoBox extends javax.swing.JDialog {

    EmpregadoController empregadoController;
    
    /** Creates new form TppmAlterarEmpregadoBox */
    public TppmAlterarEmpregadoBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        empregadoController = new EmpregadoController();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cpfInput = new javax.swing.JTextField();
        btAlterarEmpregado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tppm.views.TppmApp.class).getContext().getResourceMap(TppmAlterarEmpregadoBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cpfInput.setText(resourceMap.getString("cpfInput.text")); // NOI18N
        cpfInput.setName("cpfInput"); // NOI18N

        btAlterarEmpregado.setText(resourceMap.getString("btAlterarEmpregado.text")); // NOI18N
        btAlterarEmpregado.setName("btAlterarEmpregado"); // NOI18N
        btAlterarEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarEmpregadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(btAlterarEmpregado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btAlterarEmpregado)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarEmpregadoActionPerformed
        String cpf = cpfInput.getText();
        try{
            Empregado empregado = empregadoController.procurarEmpregado(cpf);
            if(empregado != null){
                fecharAlterarEmpregadoBox();
                abrirBoxAlterarEmpregadoForm(empregado);
            }
            else{
                Utils.exibeErro(this, "Não existe nenhum empregado com esse cpf cadastrado!");
            }
        }
        catch(EmpregadoDAOException e){
            Utils.exibeErro(this, "Erro ao procurar o empregado!");
        }
        catch(ValidacaoEmpregadoException e){
            Utils.exibeErro(this, e.getMessage());
        }
    }//GEN-LAST:event_btAlterarEmpregadoActionPerformed
    
    public void fecharAlterarEmpregadoBox() {
        dispose();
    }
    
    private void abrirBoxAlterarEmpregadoForm(Empregado empregado){
        JFrame mainFrame = TppmApp.getApplication().getMainFrame();
        alterarEmpregadoFormBox = new TppmAlterarEmpregadoFormBox(empregado);
        alterarEmpregadoFormBox.setLocationRelativeTo(mainFrame);
        TppmApp.getApplication().show(alterarEmpregadoFormBox);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TppmAlterarEmpregadoBox dialog = new TppmAlterarEmpregadoBox(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarEmpregado;
    private javax.swing.JTextField cpfInput;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private JFrame alterarEmpregadoFormBox;
}
