/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TppmAlterarEmpregadoFormBox.java
 *
 * Created on Jul 29, 2013, 22:32:33 AM
 */
package tppm.views;

import tppm.controllers.EmpregadoController;
import tppm.domains.Empregado;
import tppm.utils.Utils;


/**
 *
 * @author Tiago Neves + Pedro Jardim
 */
public class TppmAlterarEmpregadoFormBox extends javax.swing.JFrame {

    EmpregadoController empregadoController;
    
    /** Creates new form TppmAlterarEmpregadoFormBox */
    public TppmAlterarEmpregadoFormBox(Empregado empregado) {
        initComponents();
        empregadoController = new EmpregadoController(this);
        preencherCampoComDadosDoEmpregadoSelecionado(empregado);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLabel = new javax.swing.JLabel();
        nomeCompletoInput = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfInput = new javax.swing.JTextField();
        sexoLabel = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox();
        dataNascimentoLabel = new javax.swing.JLabel();
        dataNascimentoInput = new javax.swing.JTextField();
        dataAdmissaoLabel = new javax.swing.JLabel();
        dataAdmissaoInput = new javax.swing.JTextField();
        salarioLabel = new javax.swing.JLabel();
        salarioInput = new javax.swing.JTextField();
        dataDesligamentoInput = new javax.swing.JTextField();
        dataDesligamentoLabel = new javax.swing.JLabel();
        btAlterarEmpregado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tppm.views.TppmApp.class).getContext().getResourceMap(TppmAlterarEmpregadoFormBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        nomeLabel.setText(resourceMap.getString("nomeLabel.text")); // NOI18N
        nomeLabel.setName("nomeLabel"); // NOI18N

        nomeCompletoInput.setText(resourceMap.getString("nomeCompletoInput.text")); // NOI18N
        nomeCompletoInput.setName("nomeCompletoInput"); // NOI18N

        cpfLabel.setText(resourceMap.getString("cpfLabel.text")); // NOI18N
        cpfLabel.setName("cpfLabel"); // NOI18N

        cpfInput.setEditable(false);
        cpfInput.setText(resourceMap.getString("cpfInput.text")); // NOI18N
        cpfInput.setName("cpfInput"); // NOI18N

        sexoLabel.setText(resourceMap.getString("sexoLabel.text")); // NOI18N
        sexoLabel.setName("sexoLabel"); // NOI18N

        sexoComboBox.setModel(EmpregadoController.obtemComboSexoModel());
        sexoComboBox.setName("sexoComboBox"); // NOI18N

        dataNascimentoLabel.setText(resourceMap.getString("dataNascimentoLabel.text")); // NOI18N
        dataNascimentoLabel.setName("dataNascimentoLabel"); // NOI18N

        dataNascimentoInput.setText(resourceMap.getString("dataNascimentoInput.text")); // NOI18N
        dataNascimentoInput.setName("dataNascimentoInput"); // NOI18N

        dataAdmissaoLabel.setText(resourceMap.getString("dataAdmissaoLabel.text")); // NOI18N
        dataAdmissaoLabel.setName("dataAdmissaoLabel"); // NOI18N

        dataAdmissaoInput.setName("dataAdmissaoInput"); // NOI18N

        salarioLabel.setText(resourceMap.getString("salarioLabel.text")); // NOI18N
        salarioLabel.setName("salarioLabel"); // NOI18N

        salarioInput.setText(resourceMap.getString("salarioInput.text")); // NOI18N
        salarioInput.setName("salarioInput"); // NOI18N

        dataDesligamentoInput.setText(resourceMap.getString("dataDesligamentoInput.text")); // NOI18N
        dataDesligamentoInput.setName("dataDesligamentoInput"); // NOI18N

        dataDesligamentoLabel.setText(resourceMap.getString("dataDesligamentoLabel.text")); // NOI18N
        dataDesligamentoLabel.setName("dataDesligamentoLabel"); // NOI18N

        btAlterarEmpregado.setText(resourceMap.getString("btAlterarEmpregado.text")); // NOI18N
        btAlterarEmpregado.setName("btAlterarEmpregado"); // NOI18N
        btAlterarEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarEmpregadoActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAlterarEmpregado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeLabel)
                            .addComponent(cpfLabel)
                            .addComponent(sexoLabel)
                            .addComponent(dataNascimentoLabel)
                            .addComponent(dataAdmissaoLabel)
                            .addComponent(salarioLabel)
                            .addComponent(dataDesligamentoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dataDesligamentoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salarioInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataAdmissaoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataNascimentoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeCompletoInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataNascimentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoLabel)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataAdmissaoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataAdmissaoLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarioLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDesligamentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDesligamentoLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAlterarEmpregado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlterarEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarEmpregadoActionPerformed
        String cpf = cpfInput.getText();
        String nome = nomeCompletoInput.getText();
        String sexo = (String) sexoComboBox.getSelectedItem();
        String dataNascimento = dataNascimentoInput.getText();
        String dataAdmissao = dataAdmissaoInput.getText();
        String salarioAtual = salarioInput.getText();
        String dataDesligamento = dataDesligamentoInput.getText();
        
        try{
            empregadoController.alterarEmpregado(cpf, nome, sexo, dataNascimento, dataAdmissao, salarioAtual, dataDesligamento);
            Utils.exibeMensagem(this, "Empregado alterado com sucesso!");
            closeAlterarEmpregadoFormBox();
        } catch(Exception e){
            Utils.exibeErro(this, e.getMessage());
        }
    }//GEN-LAST:event_btAlterarEmpregadoActionPerformed
    
    private void preencherCampoComDadosDoEmpregadoSelecionado(Empregado empregado){
        try{
            preencherCampoCPF(empregado);
            preencherCampoNome(empregado);
            preencherCampoSexo(empregado);
            preencherCampoDataNascimento(empregado);
            preencherCampoDataAdmissao(empregado);
            preencherCampoSalario(empregado);
            preencherCampoDataDesligamento(empregado);
        } catch(Exception e){
            Utils.exibeErro(this, "Oops, houve um erro ao carregar os dados do empregado!");
        }
    }
    
    private void preencherCampoCPF(Empregado empregado){
        if(empregado.getCpf() != null)
            cpfInput.setText(empregado.getCpf());
    }
    
    private void preencherCampoNome(Empregado empregado){
        if(empregado.getNome() != null)
            nomeCompletoInput.setText(empregado.getNome());
    }
    
    private void preencherCampoSexo(Empregado empregado){
        if(empregado.getSexo() != null)
            sexoComboBox.setSelectedItem(empregado.getSexo());
    }
    
    private void preencherCampoDataNascimento(Empregado empregado){
        if(empregado.getDataNascimento() != null)
            dataNascimentoInput.setText(Utils.converterDataParaString(empregado.getDataNascimento()));
    }
    
    private void preencherCampoDataAdmissao(Empregado empregado){
        if(empregado.getDataAdmissao() != null)
            dataAdmissaoInput.setText(Utils.converterDataParaString(empregado.getDataAdmissao()));
    }
    
    private void preencherCampoSalario(Empregado empregado){
        if(empregado.getSalarioAtual() != null)
            salarioInput.setText(empregado.getSalarioAtual().toString());
    }
    
    private void preencherCampoDataDesligamento(Empregado empregado){
        if(empregado.getDataDesligamento() != null)
            dataDesligamentoInput.setText(Utils.converterDataParaString(empregado.getDataDesligamento()));
    }
    
    public void closeAlterarEmpregadoFormBox() {
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarEmpregado;
    private javax.swing.JTextField cpfInput;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField dataAdmissaoInput;
    private javax.swing.JLabel dataAdmissaoLabel;
    private javax.swing.JTextField dataDesligamentoInput;
    private javax.swing.JLabel dataDesligamentoLabel;
    private javax.swing.JTextField dataNascimentoInput;
    private javax.swing.JLabel dataNascimentoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeCompletoInput;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField salarioInput;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JComboBox sexoComboBox;
    private javax.swing.JLabel sexoLabel;
    // End of variables declaration//GEN-END:variables
}
